name: Notifications
run-name: ${{ github.actor }} has updated Repo
on:
  push:
  pull_request:
    types:
      - opened
  pull_request_review:
    types:
      - submitted

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Type Of Event
        id: typeOfEvent
        run: echo ::set-output name=event::${{ toJson(github.event_name) }}

      - name: Send Notification on Push
        if: ${{ steps.typeOfEvent.outputs.event == 'push' }}
        run: |
          echo "Mai aagaya :)"

      - name: Send Notification on Pull Request
        if: ${{ steps.typeOfEvent.outputs.event == 'pull_request' && github.event.action == 'opened' }}
        run: |
          echo "May I come in ;)"

      
      - name: Send Notification on Merge
        if: ${{ steps.typeOfEvent.outputs.event == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged }}
        run: |
          echo "Ye bandhan toh... "
